### ISSUE TITLE
Stil working ?

### ISSUE THREAD

**Issue by whoo** [nigelsdtech/tenrox-utils#1]
Hola,

i tried to test you nodejs software ... changing your default URL to mine.
But still not working ... is your software still accurate.

```javascript
undefined:1
Invalid token.
^

SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/tmp/node_modules/tenrox-utils/TenroxUtils.js:188:20)
    at Request.self.callback (/tmp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/tmp/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/tmp/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
```

**Comment by nigelsdtech** [comment]
Hey there. I haven't used this library in about 2 years so not sure if things have changed since then. Happy to merge a PR.
